### ISSUE TITLE
Missing example content

### ISSUE THREAD

**Issue by thavlik** [itaysk/kube-imagepuller#2]
Howdy! This thing worked perfectly after figuring out how it's supposed to be used. If anyone has difficulty getting it to work, I'd like to provide this additional instruction:

1. Create a project dir, clone the repository into it
```
mkdir my-project && cd my-project
git clone https://github.com/itaysk/kube-imagepuller.git
```

2.  (Only necessary for private repositories) add your registry credentials with the name `regcred` in the same namespace you want the daemonset. Notice we're going to use a `generic` secret  created from a file, but you can use any other method for creating an image pull secret:
```
kubectl create namespace precache
kubectl create secret generic regcred \
    -n precache \
    --from-file=.dockerconfigjson=$HOME/.docker/config.json \
    --type=kubernetes.io/dockerconfigjson
```
3. Create some yaml for tiller (if not already done) and the chart to be installed:
tiller.yaml:
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
```
precache-my-image-values.yaml (notice the essential `docker://` and `docker-daemon:` prefixes):
```
src:
  image: docker://registry.mywebsite.com/myusername/myimage:latest
  pullSecret: # uses `regcred` within the namespace of the helm release
    enabled: true 
dst:
  image: docker-daemon:registry.mywebsite.com/myusername/myimage:latest
```

3. Initialize helm (if not already) and install the chart
```
kubectl apply -f tiller.yaml # skip if helm is already installed
helm init --service-account tiller --upgrade # skip if helm is already installed
# install from the cloned repo
helm install --name precache-my-image \
    --namespace precache \
    -f precache-my-image-values.yaml \
    kube-imagepuller/imagepuller
```
The DaemonSet can take a very long time before the container is created. In my case, I had a 2.4Gb image that was cached on a large cluster, which held the pod statuses at `Init:0/1` for over half an hour.

This chart does *exactly* what I need. Good work!
